name: Build and Test Open PR

on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Variant to build and test'
        required: true
        default: 'open-pr'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew assemble
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: test
        run: ./gradlew test