name: Build and Test Open PR

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4.1.1
    - name: build
      run: ./gradlew assemble
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build
    steps:
    - uses: actions/checkout@v4.1.1
    - name: test
      run: ./gradlew test